# Default permissions for the app-control plugin

"$schema" = "../schemas/default.schema.json"

[default]
description = "Allows controlling app lifecycle (minimize, close, exit) and checking foreground state."
permissions = [
    "allow-minimize_app",
    "allow-close_app",
    "allow-exit_app",
    "allow-is_app_in_foreground"
]
