# Default permissions for the app-control plugin

"$schema" = "../schemas/default.schema.json"

[default]
description = "Allows controlling app lifecycle (minimize, close, exit) and checking foreground state."
permissions = [
    "plugin:app-control|minimize_app",
    "plugin:app-control|close_app",
    "plugin:app-control|exit_app",
    "plugin:app-control|is_app_in_foreground"
]
